FROM us-west1-docker.pkg.dev/gcp-security-dev-curriculum/elmer-repo/elmerbase:0.1.3

WORKDIR /physics
COPY ELMERSOLVER_STARTINFO waveguide.sif run_elmer.sh /physics/
COPY bent_waveguide2 /physics/bent_waveguide2
